In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Sample_File.csv')

In [3]:
df.head()

    Name  Age       City
0  Rensi   20     Rajkot
1   Amit   21  Ahmedabad
2   Neha   19      Surat

In [4]:
df.to_json('Sample_File_json.json')

In [5]:
df=pd.read_json('Sample_File_json.json')

In [6]:
df

    Name  Age       City
0  Rensi   20     Rajkot
1   Amit   21  Ahmedabad
2   Neha   19      Surat

In [11]:
df.to_csv('Sample_File_Excel.csv', index=False)

In [17]:
df = pd.read_csv('Sample_File_Excel.csv')

In [18]:
df

    Name  Age       City
0  Rensi   20     Rajkot
1   Amit   21  Ahmedabad
2   Neha   19      Surat

In [20]:
df.to_csv('SampleFilegzip.gz', compression='gzip', index=False)

In [22]:
df = pd.read_csv('SampleFilegzip.gz')

In [23]:
df

    Name  Age       City
0  Rensi   20     Rajkot
1   Amit   21  Ahmedabad
2   Neha   19      Surat